name: Spring Server CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 작동

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17  # 원하는 Java 버전으로 변경
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - run: mkdir -p ./src/main/resources
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Deploy to Server
        uses: actions/checkout@v3

      - run: docker build -t thewayhome-server:0.0.1 .
      - run: docker-compose build

          # 서버에 애플리케이션 배포 스크립트 실행
          # 예: scp, SSH, Docker, Kubernetes 등을 사용하여 배포

